### ISSUE TITLE
[Styles] - Improve Login page 

### ISSUE THREAD

**Issue by danimc** [danimc/next-dashboard-template#3]
The current login page, with its stark two-color design, becomes visually unappealing when incorrect credentials are entered. We need to enhance the design of this page.

![image](https://github.com/user-attachments/assets/5500fc85-a816-41b1-a7be-b201a4c5409e)

**Comment by jovdim** [comment]
**Hi**,

I’m a beginner contributor, but I’m excited to help improve this project. I’ve worked on creating custom authentication templates using Auth.js (formerly NextAuth.js)  too, and I believe I can contribute by improving the styling and enhancing the validation.

Thanks!

**Comment by l-daniel-mora** [comment]
> **Hi**,
> 
> I’m a beginner contributor, but I’m excited to help improve this project. I’ve worked on creating custom authentication templates using Auth.js (formerly NextAuth.js)  too, and I believe I can contribute by improving the styling and enhancing the validation.
> 
> Thanks!

Hey buddy, 

Thanks for your support,  feel free to contribute 😀

**Comment by jovdim** [comment]
Hi, I made my first pull request.
